import auth, home, rollerShutter, lightSensor; 
import time   

# Example usage
if __name__ == "__main__":
    # Register a new user
    auth.register_user("ma", "aaaa")

    # Authenticate the user and get a JWT token
    jwt_token = auth.authenticate_user("ma", "aaaa")
    
    print("HOME CREATE")
    home.createHome(jwt_token, "Trudda")
    time.sleep(0.5)
    print("HOME CREATE")
    home.createHome(jwt_token, "Truddo")
    time.sleep(0.5)
    print("LIGHT SENSOR CREATE")
    lightSensor.createLightSensor(jwt_token, "SensoreLuce", "Trudda")
    print("LIGHT SENSOR DELETE")
    lightSensor.deleteLightSensor(jwt_token, 1)
    print("LIGHT SENSOR CREATE")
    lightSensor.createLightSensor(jwt_token, "SensoreAce", "Trudda")
    print("GET ALL LIGHT SENSORS")
    lightSensor.getAllLightSensor(jwt_token)
    print("LIGHT SENSOR MODIFY NAME")
    lightSensor.patchNameLightSensor(jwt_token, 2, "SensoreLucio")
    print("LIGHT SENSOR MODIFY VALUE")
    lightSensor.patchValueLightSensor(jwt_token, 2, 2)   
    print("LIGHT SENSOR MODIFY HOME")
    lightSensor.patchHomeLightSensor(jwt_token, 2, "Truddo")
    print("GET ALL LIGHT SENSORS")
    lightSensor.getAllLightSensor(jwt_token)
    print("GET HOMES")
    home.getAllHomes(jwt_token)
    
    
    '''
    print("HOME DELETE")
    home.deleteHome(jwt_token, 1)
    time.sleep(0.5)
    print("HOME CREATE 2")
    home.createHome(jwt_token, "Trudda")
    time.sleep(0.5)
    print("HOME MODIFY")
    home.putHome(jwt_token,2,"Trodda")
    time.sleep(0.5)
    
    time.sleep(0.5)
    print("ROLLER SHUTTER CREATE")
    rollerShutter.createRollerShutter(jwt_token, "Finestra", "Trodda")
    time.sleep(0.5)
    print("ROLLER SHUTTER DELETE")
    rollerShutter.deleteRollerShutter(jwt_token,1)
    time.sleep(0.5)
    print("GET ALL ROLLER SHUTTER")
    rollerShutter.getAllRollerShutter(jwt_token)
    time.sleep(0.5)
    print("GET HOMES")
    home.getAllHomes(jwt_token)
    time.sleep(0.5)
    print("ROLLER SHUTTER CREATE")
    rollerShutter.createRollerShutter(jwt_token, "Finetrone", "Trodda")
    time.sleep(0.5)
    print("GET ALL ROLLER SHUTTER")
    rollerShutter.getAllRollerShutter(jwt_token)
    time.sleep(0.5)
    print("GET HOMES")
    home.getAllHomes(jwt_token)
    time.sleep(0.5)
    print("ROLLER SHUTTER MODIFY NAME")
    rollerShutter.patchNameRollerShutter(jwt_token, 2, "Finestrina")
    time.sleep(0.5)
    print("GET ALL ROLLER SHUTTER")
    rollerShutter.getAllRollerShutter(jwt_token)
    time.sleep(0.5)
    print("ROLLER SHUTTER MODIFY OPENING")
    rollerShutter.patchOpeningRollerShutter(jwt_token, 2, 2)
    time.sleep(0.5)
    print("GET ALL ROLLER SHUTTER")
    rollerShutter.getAllRollerShutter(jwt_token)
    time.sleep(0.5)
    print("HOME CREATE 3")
    home.createHome(jwt_token, "Casteddu")
    time.sleep(0.5)
    print("GET HOMES")
    home.getAllHomes(jwt_token)
    time.sleep(0.5)
    print("ROLLER SHUTTER MODIFY HOME")
    rollerShutter.patchHomeRollerShutter(jwt_token, 2, "Casteddu")
    time.sleep(0.5)
    print("GET ALL ROLLER SHUTTER")
    rollerShutter.getAllRollerShutter(jwt_token)
    time.sleep(0.5)
    print("GET HOMES")
    home.getAllHomes(jwt_token)
    '''
    