name: RoutineAgent
services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    image: routine_agent_2025
    container_name: routineAgent
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5433/ROUTINEAGENT
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: ESIT2024
    depends_on:
      db:
        condition: service_healthy
    networks:
      - my-network2
  db:
    image: postgres
    container_name: postgres2
    ports:
      - "5433:5433"
    environment:
      POSTGRES_DB: ROUTINEAGENT
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ESIT2024
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres-data:/var/lib/postgresql/data
    command: ["postgres", "-p", "5433"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d ROUTINEAGENT -p 5433 -h localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - my-network2
volumes:
  postgres-data:


networks:
  my-network2:
    driver: bridge

